name: edu_manager
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # Routing
  go_router: ^14.6.0
  
  # Functional Programming
  fpdart: ^1.1.0
  
  # Data Class & Serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  supabase_flutter: ^2.6.0
  flutter_dotenv: ^5.1.0
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  uuid: ^4.5.2
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
